/*
 * The MIT License
 *
 * *** Copyright © Long Zhang(kanch)
 * *** Email: kanchisme@gmail.com
 * *** Code generated on 2018-04-21 18:05:39.080234
 * *** Code generated by Database Insights Localization Generation Tool
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package dbi.localization;

/**
 *
 * @author kanch
 */
public class langID {
    //@DBI_LANGGEN_TOOL_BEGIN
	
	public static int JSP_CONSOLE_CREDENTIAL_MGR_TITLE = 2000;
	public static int JSP_CONSOLE_CREDENTIAL_MGR_CSUM_PRE = 2001;
	public static int JSP_CONSOLE_CREDENTIAL_MGR_CSUM_SUF = 2002;
	public static int JSP_CONSOLE_CREDENTIAL_MGR_BUTTON_ADD = 2003;
	public static int JSP_CONSOLE_CREDENTIAL_MGR_TIP_SEARCH = 2004;
	public static int JSP_CONSOLE_CREDENTIAL_MGR_BUTTON_SEARCH = 2005;
	public static int JSP_CONSOLE_CREDENTIAL_MGR_TABLE_DBNAME = 2006;
	public static int JSP_CONSOLE_CREDENTIAL_MGR_TABLE_HOST = 2007;
	public static int JSP_CONSOLE_CREDENTIAL_MGR_TABLE_ACCOUNT = 2008;
	public static int JSP_CONSOLE_CREDENTIAL_MGR_TABLE_PASSWORD = 2009;
	public static int JSP_CONSOLE_CREDENTIAL_MGR_TABLE_OPERATIONS = 2010;
	public static int JSP_CONSOLE_CREDENTIAL_MGR_TABLE_OPERATION_SAVE = 2011;
	public static int JSP_CONSOLE_CREDENTIAL_MGR_TABLE_OPERATION_EDIT = 2012;
	public static int JSP_CONSOLE_CREDENTIAL_MGR_TABLE_OPERATION_DELETE = 2013;
	public static int JSP_CONSOLE_CREDENTIAL_MGR_TIP_FAILED_DELETE = 2014;
	public static int JSP_CONSOLE_CREDENTIAL_MGR_TIP_SUCCESS_DELETE = 2015;
	public static int JSP_CONSOLE_CREDENTIAL_MGR_TIP_FAILED_UPDATE = 2016;
	public static int JSP_CONSOLE_CREDENTIAL_MGR_TIP_SUCCESS_UPDATE = 2017;
	public static int JSP_CONSOLE_CREDENTIAL_MGR_TIP_NO_DATA = 2018;
	public static int JSP_CONSOLE_CREDENTIAL_ADD_TITLE = 2019;
	public static int JSP_CONSOLE_CREDENTIAL_ADD_SELECT = 2020;
	public static int JSP_CONSOLE_CREDENTIAL_ADD_HOST = 2021;
	public static int JSP_CONSOLE_CREDENTIAL_ADD_DBNAME = 2022;
	public static int JSP_CONSOLE_CREDENTIAL_ADD_USERNAME = 2023;
	public static int JSP_CONSOLE_CREDENTIAL_ADD_PASSWORD = 2024;
	public static int JSP_CONSOLE_CREDENTIAL_ADD_IAGREE_PRE = 2025;
	public static int JSP_CONSOLE_CREDENTIAL_ADD_IAGREE_SUF = 2026;
	public static int JSP_CONSOLE_CREDENTIAL_ADD_BUTTON_ADD = 2027;
	public static int JSP_CONSOLE_CREDENTIAL_ADD_BUTTON_CANCEL = 2028;
	public static int JSP_CONSOLE_CREDENTIAL_ADD_HOST_TIP = 2029;
	public static int JSP_CONSOLE_CREDENTIAL_ADD_DBNAME_TIP = 2030;
	public static int JSP_CONSOLE_CREDENTIAL_ADD_USERNAME_TIP = 2031;
	public static int JSP_CONSOLE_CREDENTIAL_ADD_PASSWORD_TIP = 2032;
	public static int JSP_CONSOLE_CREDENTIAL_ADD_TIP_AGREEMENT = 2033;
	public static int JSP_CONSOLE_CREDENTIAL_ADD_TIP_CHECKING = 2034;
	public static int JSP_CONSOLE_CREDENTIAL_ADD_TIP_FAILED = 2035;
	public static int JSP_CONSOLE_CREDENTIAL_ADD_TIP_SUCCESS = 2036;
	public static int JSP_CONSOLE_FOOTER_HOME = 2037;
	public static int JSP_CONSOLE_FOOTER_SERVICE = 2038;
	public static int JSP_CONSOLE_FOOTER_POLICY = 2039;
	public static int JSP_SIGNIN_PAGE_TITLE = 2040;
	public static int JSP_SIGNIN_FORM_TITLE = 2041;
	public static int JSP_SIGNIN_LABEL_EMAIL = 2042;
	public static int JSP_SIGNIN_LABEL_PASSWORD = 2043;
	public static int JSP_SIGNIN_LABEL_REMEMBERME = 2044;
	public static int JSP_SIGNIN_LABEL_LOGIN = 2045;
	public static int JSP_SIGNIN_LABEL_PROBLEMLOGIN = 2046;
	public static int JSP_SIGNIN_JS_NAVTITLE = 2047;
	public static int JSP_SIGNIN_TIP_FAILED = 2048;
	public static int JSP_SIGNIN_TIP_SUCCESS = 2049;
	public static int JSP_SIGNUP_LABEL_USERNAME = 2050;
	public static int JSP_SIGNUP_LABEL_EMAIL = 2051;
	public static int JSP_SIGNUP_LABEL_PASSWORD = 2052;
	public static int JSP_SIGNUP_LABEL_CONFIRMPASSWORD = 2053;
	public static int JSP_SIGNUP_BUTTON_SIGNUP = 2054;
	public static int JSP_SIGNUP_BUTTON_LOGIN = 2055;
	public static int JSP_SIGNUP_INFO_USERNAME = 2056;
	public static int JSP_SIGNUP_INFO_EMAIL = 2057;
	public static int JSP_SIGNUP_INFO_PASSWORD = 2058;
	public static int JSP_SIGNUP_INFO_AGGREMENT = 2059;
	public static int JSP_CONSOLE_SETTINGS_TITLE = 2060;
	public static int JSP_CONSOLE_SETTINGS_LABEL_REGISTEDON = 2061;
	public static int JSP_CONSOLE_SETTINGS_LABEL_STATUS = 2062;
	public static int JSP_CONSOLE_SETTINGS_LABEL_LASTLOGIN = 2063;
	public static int JSP_CONSOLE_SETTINGS_LABEL_USERNAME = 2064;
	public static int JSP_CONSOLE_SETTINGS_LABEL_EMAIL = 2065;
	public static int JSP_CONSOLE_SETTINGS_BUTTON_SAVE = 2066;
	public static int JSP_CONSOLE_SETTINGS_LABEL_OLDPASSWORD = 2067;
	public static int JSP_CONSOLE_SETTINGS_LABEL_NEWPASSWORD = 2068;
	public static int JSP_CONSOLE_SETTINGS_LABEL_COMFIRM_NEWPASSWORD = 2069;
	public static int JSP_CONSOLE_SETTINGS_TIP_USERNAME = 2070;
	public static int JSP_CONSOLE_SETTINGS_TIP_EMAIL = 2071;
	public static int JSP_CONSOLE_SETTINGS_LABEL_WARNING = 2072;
	public static int JSP_NAV_SIDE_OVERVIEW = 2073;
	public static int JSP_NAV_SIDE_REPORTS = 2074;
	public static int JSP_NAV_SIDE_REALTIME = 2075;
	public static int JSP_NAV_SIDE_ANALYTICS = 2076;
	public static int JSP_NAV_SIDE_AUTO = 2077;
	public static int JSP_NAV_SIDE_CROSSTABLE = 2078;
	public static int JSP_NAV_SIDE_CUSTOMIZE = 2079;
	public static int JSP_NAV_SIDE_OTHERS = 2080;
	public static int JSP_NAV_SIDE_CREDENTIALS = 2081;
	public static int JSP_NAV_SIDE_LOGS = 2082;
	public static int JSP_NAV_SIDE_SETTINGS = 2083;
	public static int JSP_NAV_SIDE_TITLE_ANALYTICS = 2084;
	public static int JSP_NAV_SIDE_TITLE_DATABASE = 2085;
	public static int JSP_NAV_SIDE_TITLE_ACCOUNT = 2086;
	public static int USER_STATUS_UNKNOW = 2087;
	public static int USER_STATUS_UNVERFIED = 2088;
	public static int USER_STATUS_NORMAL = 2089;
	public static int USER_STATUS_RESTRICTED = 2090;
	//@DBI_LANGGEN_TOOL_END
    
}
