/*
 * The MIT License
 *
 * *** Copyright © Long Zhang(kanch)
 * *** Email: kanchisme@gmail.com
 * *** Code generated on 2018-04-12 15:08:23.395356
 * *** Code generated by Database Insights Localization Generation Tool
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package dbi.localization;

/**
 *
 * @author kanch
 */
public class langID {
    //@DBI_LANGGEN_TOOL_BEGIN
	
	public static int JSP_NAV_SIDE_OVERVIEW = 2000;
	public static int JSP_NAV_SIDE_REPORTS = 2001;
	public static int JSP_NAV_SIDE_REALTIME = 2002;
	public static int JSP_NAV_SIDE_ANALYTICS = 2003;
	public static int JSP_NAV_SIDE_AUTO = 2004;
	public static int JSP_NAV_SIDE_CROSSTABLE = 2005;
	public static int JSP_NAV_SIDE_CUSTOMIZE = 2006;
	public static int JSP_NAV_SIDE_OTHERS = 2007;
	public static int JSP_NAV_SIDE_CREDENTIALS = 2008;
	public static int JSP_NAV_SIDE_LOGS = 2009;
	public static int JSP_NAV_SIDE_SETTINGS = 2010;
	public static int JSP_NAV_SIDE_TITLE_ANALYTICS = 2011;
	public static int JSP_NAV_SIDE_TITLE_DATABASE = 2012;
	public static int JSP_NAV_SIDE_TITLE_ACCOUNT = 2013;
	public static int USER_STATUS_UNKNOW = 2014;
	public static int USER_STATUS_UNVERFIED = 2015;
	public static int USER_STATUS_NORMAL = 2016;
	public static int USER_STATUS_RESTRICTED = 2017;
	//@DBI_LANGGEN_TOOL_END
    
}
