/*
 * The MIT License
 *
 * *** Copyright © Long Zhang(kanch)
 * *** Email: kanchisme@gmail.com
 * *** Code created on Apr 19 2018
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package dbi.analyzer;

/**
 *
 * @author kanch
 */
public class ChartOption {

    public static String OPTION_HISTOGRAM = "option = {"
            + "        title : {"
            + "        text: '@TITLE',"
            + "        subtext: '@SUBTITLE',"
            + "        x:'center'"
            + "    },"
            + "    xAxis: {"
            + "        type: 'category',"
            + "        data: @XDATA"
            + "    },"
            + "    yAxis: {"
            + "        type: 'value'"
            + "    },"
            + "    series: [{"
            + "        data: @YDATA,"
            + "        type: 'bar'"
            + "    }]"
            + "};";

    public static String OPTION_LINE = "option = {"
            + "    title : {"
            + "        text: '@TITLE',"
            + "        subtext: '@SUBTITLE',"
            + "        x:'center'"
            + "    },"
            + "    xAxis: {"
            + "        type: 'category',"
            + "        data: @XDATA"
            + "    },"
            + "    yAxis: {"
            + "        type: 'value'"
            + "    },"
            + "    series: [{"
            + "        data: @YDATA,"
            + "        type: 'line'"
            + "    }]"
            + "};";

    public static String OPTION_PIE = "option = {"
            + "    title : {"
            + "        text: '@TITLE',"
            + "        subtext: '@SUBTITLE',"
            + "        x:'center'"
            + "    },"
            + "    tooltip : {"
            + "        trigger: 'item',"
            + "        formatter: \"{a} <br/>{b} : {c} ({d}%)\""
            + "    },"
            + "    legend: {"
            + "        orient: 'vertical',"
            + "        right: 10,"
            + "        top: 100,"
            + "        bottom: 20,"
            + "        data: [@XDATA]"
            + "    },"
            + "    series : ["
            + "        {"
            + "            name: '@INFO',"
            + "            type: 'pie',"
            + "            radius : '55%',"
            + "            center: ['50%', '60%'],"
            + "            data:["
            + "                @YDATA"
            + "            ],"
            + "            itemStyle: {"
            + "                emphasis: {"
            + "                    shadowBlur: 10,"
            + "                    shadowOffsetX: 0,"
            + "                    shadowColor: 'rgba(0, 0, 0, 0.5)'"
            + "                }"
            + "            }"
            + "        }"
            + "    ]"
            + "};";

    public static String OPTION_SCATTER_WITH_AVERAGE = "option = {"
            + "    title: {"
            + "        text: '@TITLE',"
            + "        subtext: '@SUBTITLE',"
            + "        x: 'center',"
            + "        y: 0"
            + "    },"
            + "    tooltip: {"
            + "        formatter: '@TOOLTIP {a}: ({c})'"
            + "    },"
            + "    xAxis: ["
            + "        {gridIndex: 0, min: 0, max: 20},"
            + "    ],"
            + "    yAxis: ["
            + "        {gridIndex: 0, min: 0, max: 15},"
            + "    ],"
            + "    series: ["
            + "        {"
            + "            name: 'value',"
            + "            type: 'scatter',"
            + "            xAxisIndex: 0,"
            + "            yAxisIndex: 0,"
            + "            data:  ["
            + "                        @DATA"
            + "                    ],"
            + "            markLine: {"
            + "                            animation: true,"
            + "                            label: {"
            + "                                normal: {"
            + "                                    formatter: '@AVERAGE_TEXT',"
            + "                                    textStyle: {"
            + "                                        align: 'bottom'"
            + "                                    }"
            + "                                }"
            + "                            },"
            + "                            lineStyle: {"
            + "                                normal: {"
            + "                                    type: 'solid'"
            + "                                }"
            + "                            },"
            + "                            tooltip: {"
            + "                                formatter: '@AVERAGE_TEXT:@AVG_Y'"
            + "                            },"
            + "                            data: [[{"
            + "                                coord: [@AVG_X1, @AVG_Y],"
            + "                                symbol: 'none'"
            + "                            }, {"
            + "                                coord: [@AVG_X2, @AVG_Y],"
            + "                                symbol: 'none'"
            + "                            }]]"
            + "                        }"
            + "        }"
            + "    ]"
            + "};";

    public static String OPTION_HISTOGRAM_FULLAREA = "option = {"
            + "        title : {"
            + "        text: '@TITLE',"
            + "        subtext: '@SUBTITLE',"
            + "        x:'center'"
            + "    },"
            + "    xAxis: {"
            + "        type: 'category',"
            + "        boundaryGap: false,"
            + "        data: [@XDATA]"
            + "    },"
            + "    yAxis: {"
            + "        type: 'value'"
            + "    },"
            + "    series: [{"
            + "        data: [@YDATA],"
            + "        type: 'line',"
            + "        areaStyle: {}"
            + "    }]"
            + "};";

    public static String OPTION_TREEMAP = "option = {"
            + "    series: [{"
            + "        type: 'treemap',"
            + "        data: [@DATA]"
            + "    }]"
            + "};";

    public static String OPTION_COUNTM2 = "app.title = '@TITLE';"
            + ""
            + "option = {"
            + "    tooltip: {"
            + "        trigger: 'item',"
            + "        formatter: \"{a} <br/>{b}: {c} ({d}%)\""
            + "    },"
            + "    legend: {"
            + "        orient: 'vertical',"
            + "        x: 'left',"
            + "        data:['??','????','????','????','????','????','??','??','??','??']"
            + "    },"
            + "    series: ["
            + "        {"
            + "            name:'@TIP_INNER',"
            + "            type:'pie',"
            + "            selectedMode: 'single',"
            + "            radius: [0, '30%'],"
            + ""
            + "            label: {"
            + "                normal: {"
            + "                    position: 'inner'"
            + "                }"
            + "            },"
            + "            labelLine: {"
            + "                normal: {"
            + "                    show: false"
            + "                }"
            + "            },"
            + "            data:["
            + "                {value:1000, name:'??', selected:true},"
            + "                {value:679, name:'????'},"
            + "                {value:1548, name:'????'}"
            + "            ]"
            + "        },"
            + "        {"
            + "            name:'@TIP_OUTER',"
            + "            type:'pie',"
            + "            radius: ['40%', '55%'],"
            + "            label: {"
            + "                normal: {"
            + "                    formatter: '{a|{a}}{abg|}\n{hr|}\n  {b|{b}?}{c}  {per|{d}%}  ',"
            + "                    backgroundColor: '#eee',"
            + "                    borderColor: '#aaa',"
            + "                    borderWidth: 1,"
            + "                    borderRadius: 4,"
            + "                    // shadowBlur:3,"
            + "                    // shadowOffsetX: 2,"
            + "                    // shadowOffsetY: 2,"
            + "                    // shadowColor: '#999',"
            + "                    // padding: [0, 7],"
            + "                    rich: {"
            + "                        a: {"
            + "                            color: '#999',"
            + "                            lineHeight: 22,"
            + "                            align: 'center'"
            + "                        },"
            + "                        // abg: {"
            + "                        //     backgroundColor: '#333',"
            + "                        //     width: '100%',"
            + "                        //     align: 'right',"
            + "                        //     height: 22,"
            + "                        //     borderRadius: [4, 4, 0, 0]"
            + "                        // },"
            + "                        hr: {"
            + "                            borderColor: '#aaa',"
            + "                            width: '100%',"
            + "                            borderWidth: 0.5,"
            + "                            height: 0"
            + "                        },"
            + "                        b: {"
            + "                            fontSize: 16,"
            + "                            lineHeight: 33"
            + "                        },"
            + "                        per: {"
            + "                            color: '#eee',"
            + "                            backgroundColor: '#334455',"
            + "                            padding: [2, 4],"
            + "                            borderRadius: 2"
            + "                        }"
            + "                    }"
            + "                }"
            + "            },"
            + "            data:["
            + "                {value:335, name:'??'},"
            + "                {value:310, name:'????'},"
            + "                {value:234, name:'????'},"
            + "                {value:135, name:'????'},"
            + "                {value:1048, name:'??'},"
            + "                {value:251, name:'??'},"
            + "                {value:147, name:'??'},"
            + "                {value:102, name:'??'}"
            + "            ]"
            + "        }"
            + "    ]"
            + "};";

    public static String OPTION_TRENDM = "option = {"
            + "    title: {"
            + "        text: '@TITLE'"
            + "    },"
            + "    tooltip : {"
            + "        trigger: 'axis',"
            + "        axisPointer: {"
            + "            type: 'cross',"
            + "            label: {"
            + "                backgroundColor: '#6a7985'"
            + "            }"
            + "        }"
            + "    },"
            + "    legend: {"
            + "        data:['????','????','????','????','????']"
            + "    },"
            + "    toolbox: {"
            + "        feature: {"
            + "            saveAsImage: {}"
            + "        }"
            + "    },"
            + "    grid: {"
            + "        left: '3%',"
            + "        right: '4%',"
            + "        bottom: '3%',"
            + "        containLabel: true"
            + "    },"
            + "    xAxis : ["
            + "        {"
            + "            type : 'category',"
            + "            boundaryGap : false,"
            + "            data : ['??','??','??','??','??','??','??']"
            + "        }"
            + "    ],"
            + "    yAxis : ["
            + "        {"
            + "            type : 'value'"
            + "        }"
            + "    ],"
            + "    series : ["
            + "        {"
            + "            name:'????',"
            + "            type:'line',"
            + "            stack: '??',"
            + "            areaStyle: {normal: {}},"
            + "            data:[120, 132, 101, 134, 90, 230, 210]"
            + "        },"
            + "        {"
            + "            name:'????',"
            + "            type:'line',"
            + "            stack: '??',"
            + "            areaStyle: {normal: {}},"
            + "            data:[220, 182, 191, 234, 290, 330, 310]"
            + "        },"
            + "        {"
            + "            name:'????',"
            + "            type:'line',"
            + "            stack: '??',"
            + "            areaStyle: {normal: {}},"
            + "            data:[150, 232, 201, 154, 190, 330, 410]"
            + "        },"
            + "        {"
            + "            name:'????',"
            + "            type:'line',"
            + "            stack: '??',"
            + "            areaStyle: {normal: {}},"
            + "            data:[320, 332, 301, 334, 390, 330, 320]"
            + "        },"
            + "        {"
            + "            name:'????',"
            + "            type:'line',"
            + "            stack: '??',"
            + "            label: {"
            + "                normal: {"
            + "                    show: true,"
            + "                    position: 'top'"
            + "                }"
            + "            },"
            + "            areaStyle: {normal: {}},"
            + "            data:[820, 932, 901, 934, 1290, 1330, 1320]"
            + "        }"
            + "    ]"
            + "};";

}
